### ISSUE TITLE
Turn Off Debug Mode

### ISSUE THREAD

**Issue by rossnanop** [hacsoc/acm.case.edu#101]
Debug mode should not be enabled when deployed.  Found this when hitting a route that existed, but looks like there is no handler for it?

<img width="788" alt="screen shot 2016-01-22 at 9 44 52 am" src="https://cloud.githubusercontent.com/assets/2287187/12513624/d3795a82-c0ec-11e5-92af-fdd49d245e6d.png">
<img width="411" alt="screen shot 2016-01-22 at 9 45 17 am" src="https://cloud.githubusercontent.com/assets/2287187/12513628/dcffcc8a-c0ec-11e5-9148-ba50ab56f46e.png">

**Comment by matthewbentley** [comment]
Fixed by updating environment on production server.
